#pragma once

#include <cmath>
#include <vector>

namespace gcodesim {

struct Vec3 {
  double x = 0.0, y = 0.0, z = 0.0;

  double& operator[](int axis) { return axis == 0 ? x : axis == 1 ? y : z; }
  double operator[](int axis) const { return axis == 0 ? x : axis == 1 ? y : z; }
};

inline Vec3 operator+(Vec3 a, Vec3 b) {
  return {a.x + b.x, a.y + b.y, a.z + b.z};
}
inline Vec3 operator-(Vec3 a, Vec3 b) {
  return {a.x - b.x, a.y - b.y, a.z - b.z};
}
inline Vec3 operator*(Vec3 a, double s) {
  return {a.x * s, a.y * s, a.z * s};
}
inline double dot(Vec3 a, Vec3 b) {
  return a.x * b.x + a.y * b.y + a.z * b.z;
}
inline double norm(Vec3 a) {
  return std::sqrt(dot(a, a));
}

// Arc planes. `first`/`second` are the in-plane axes, `normal` the axis an
// arc can also travel along (helix). first x second = normal, so "counter-
// clockwise" always means counter-clockwise seen from the +normal side.
enum class Plane { XY, ZX, YZ };  // G17, G18, G19

struct PlaneAxes {
  int first, second, normal;
};
PlaneAxes axes_of(Plane p);

enum class MoveType { Rapid, Linear, Arc, Dwell, ToolChange, Pause };

// One explicit move with nothing left to look up: all modal state has been
// applied. Positions are the tool tip in work coordinates, in mm; add
// `machine_offset` to get machine coordinates.
struct Segment {
  MoveType type = MoveType::Linear;
  Vec3 start, end;

  // arcs only
  Vec3 center;  // on the start's plane level
  Plane plane = Plane::XY;
  double sweep = 0.0;  // signed angle in radians, + is counter-clockwise

  double feed = 0.0;  // mm/min, 0 = never set
  double spindle_rpm = 0.0;
  bool spindle_on = false;
  int tool = 0;             // loaded tool, 0 = none
  Vec3 machine_offset;      // work offset + G92 + tool length
  double dwell_s = 0.0;     // Dwell only
  bool from_cycle = false;  // generated by a drilling cycle (G81-G83)
  int line = 0;

  bool is_motion() const {
    return type == MoveType::Rapid || type == MoveType::Linear || type == MoveType::Arc;
  }
  bool is_cutting() const { return type == MoveType::Linear || type == MoveType::Arc; }
};

double arc_radius(const Segment& s);
double length(const Segment& s);

// Point at fraction t in [0, 1] of the way along the move.
Vec3 point_at(const Segment& s, double t);

// Unit direction of travel at t = 0 / t = 1. Zero vector for zero-length moves.
Vec3 start_direction(const Segment& s);
Vec3 end_direction(const Segment& s);

// Points along the move, including both ends; arcs are split so no chord
// strays more than `tolerance` mm from the true arc.
std::vector<Vec3> tessellate(const Segment& s, double tolerance = 0.01);

// Signed sweep from start to end around `center` in `plane`.
// A full circle (start == end) gives +-2*pi, never 0.
double arc_sweep(Vec3 start, Vec3 end, Vec3 center, Plane plane, bool clockwise);

}  // namespace gcodesim
